config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:index, :show, :edit] do
    resources :formulas, only: [:index]
  end
  resources :salon_connections, only: [:create, :destroy]
  resources :formulas, except: [:index]

  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :salon_connections
  has_many :salon_users, through: :salon_connections
  has_many :inverse_salon_connections, class_name: "SalonConnection", foreign_key: "salon_user_id"
  has_many :inverse_salon_users, through: :inverse_salon_connections, source: :user

  # artists.guest_formulas
  has_many :guest_formulas, foreign_key: :artist_id, class_name: 'Formula'

  # client.formulas
  has_many :formulas, foreign_key: :client_id

  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :set_default_role, if: :new_record?

  validates :first_name, :last_name, presence: true, length: { maximum: 20 }
  validates_format_of :email, with: email_regexp

  enum role: [:client, :artist, :premium, :admin]

  # scope :confirmed_client, -> { where("confirmed_at IS NOT NULL AND role = 0") }
  scope :confirmed_artist, -> { where("confirmed_at IS NOT NULL AND role = 1") }

  def set_default_role
    self.role ||= :client
  end

  def full_name
    if self.first_name && self.last_name
      "#{self.first_name.capitalize} #{self.last_name}"
    else
      "#{self.email}"
    end
  end

  def self.matches(user_id)
    Formula.where('client_id = ?', user_id)
  end

  def connection_ids
    # return User.id's connected to self in array
    puts "finding connections for ##{self.id}:"
    ids = []
    SalonConnection.where("user_id = ? OR salon_user_id = ?", self.id, self.id ).map { |connection|
       ids << if connection.user_id == self.id
               connection.salon_user_id
             else
               connection.user_id
             end
    };
    ids
  end

  # SEARCH QUERY
  def self.search(search)
      if search.split.count > 1
        terms = search.split
        return where("first_name LIKE ? OR last_name LIKE ?", "%#{terms.first}%", "%#{terms.last}%" )
      else
        return where("email LIKE ? OR first_name LIKE ? OR last_name LIKE ?", "%#{search}%","%#{search}%","%#{search}%" )
      end
  end

  def invite_new(email)
    if User.find_by(email: email).empty?
      puts "message sent!"
      user = User.invite!( email, self)
      puts self
      self.increment!(:invitations_count)
    end
    user
  end

  def is_self?(user)
      self == user
  end

  def author?(formula)
    self.id == formula.artist_id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # include DeviseInvitable::Inviter

  def index

    @users =  if current_user.artist?
                  current_user.salon_users # client list
              elsif current_user.client?
                  User.all.where(role: 1) # display artists
              else
                  User.all # admin view
              end

    unless params[:search].nil? || params[:search].strip.empty?
      array = User.search(params[:search].strip)
      @users =  if current_user.client?
                  # display only artists
                  array.flatten.delete_if { |i| i.id === current_user.id || i.client? }
                else
                  # dispay artists and clients
                  array.flatten.delete_if { |i| i.id == current_user.id }
                end
    end

    if params[:email] && @users.empty?
      current_user.invite_new(params[:email])
    end

  end

  def show

    @user = User.find(params[:id])

    unless current_user.artist? && @user.client? || current_user.connection_ids.include?(@user.id) || current_user.is_self?(@user)
      flash[:alert] = "You do can not access this profile. Consider connecting with them first"
      redirect_to request.referrer || root_path
    end

    # @connection_ids = current_user.connection_ids

    @formulas = case
                when current_user.is_self?(@user)
                  if @user.client?
                    # guests can see their entire history
                    @user.formulas.first(4)
                  else
                    # artists would see their complete client history
                    @user.guest_formulas.first(6)
                  end
                when current_user.client? && @user.artist?
                  # when a client visists an artists page, should only return their own client history with specific artist.
                  @user.guest_formulas.where('client_id = ?', current_user.id)
                when current_user.artist?
                  # when current_user is an artists any profile they visit not their own lists their formulas (as a client)
                  @user.formulas.first(10)
                when current_user.client? && @user.client?
                  []
                end

    @formula = @formulas ? @formulas.first : nil

  end

  def edit    # non Devise edit page which also contains a dashboard like info

    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "You do not have access to this profile"
      redirect_to edit_user_path(current_user)
    end
  end

end

app/helpers/user_helper.rb
module UserHelper
    
    def joined_with?(user)
        
        (current_user.salon_connections.where("salon_user_id = ?", user.id).exists? &&
            user.inverse_salon_connections.where("user_id = ?", current_user.id).exists?) ||
        (user.salon_connections.where("salon_user_id = ?", current_user.id).exists? &&
            current_user.inverse_salon_connections.where("user_id = ?", user.id).exists? )
        
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
    
    def joined_with?(user)
        return false unless current_user
        # check for reciprocal link between two users
        (current_user.salon_connections.where("salon_user_id = ?", user.id).exists? &&
            user.inverse_salon_connections.where("user_id = ?", current_user.id).exists?) ||
        (user.salon_connections.where("salon_user_id = ?", current_user.id).exists? &&
            current_user.inverse_salon_connections.where("user_id = ?", user.id).exists? )
    end
    
end

app/views/users/_user_links.html.erb
<div class="">

  <!-- if current user has guests or clients -->
  <% if current_user.salon_users.include?(user) || current_user.inverse_salon_users.include?(user) || current_user.is_self?(user) %>

      <!-- if current_user is an artist? -->
      <% if current_user.artist? %>

          <% if formula %>
              <!--copy-->
              <%= link_to formulas_path(copy: formula.id), id: 'formula-copy', method: :create, class: 'btn btn-sm btn-default' do %>
                <%= icon('copy') %> <span class="hidden-xs">copy <span class="hidden-sm">this</span> formula</span>
              <% end %>
              <!--edit-->
              <% if current_user.author?(formula) %>
                <%= link_to edit_formula_path(formula), id: 'formula-edit', class: 'btn btn-sm btn-default'  do %>
                  edit <span class="hidden-xs">formula</span>
                <% end %>
              <% end %>

          <% end %>
            <!--new-->
          <% if !current_user.is_self?(user) %>
            <%= link_to new_formula_path(requested_user: user), id: 'formula-new' ,class: 'btn btn-sm btn-default hidden-xs' do %>
              <%= icon('pencil-square-o') %> <span class="">create <span class="hidden-sm">new </span>formula</span>
            <% end %>
          <% end %>

      <% end %>

      <div class='btn-group pull-right'>

        <% if history %>
          <%= link_to user_formulas_path(user), class: 'btn btn-sm btn-default', title: "User History" do %>
            <i class="fa fa-book"></i> <span class="hidden-sm hidden-xs">User</span> History
          <% end %>
        <% end %>

        <% if !current_user.is_self?(user) %>
          <%= link_to salon_connection_path(id: user.id), class: 'btn btn-sm btn-success blue-border', method: :delete, title: "Remove Connection", data: { confirm: "disconnect from #{user.full_name}"} do %>
            <i class="fa fa-user-times"></i>
          <% end %>
        <% end %>

      </div>

  <% else %>

    <div class='btn-group pull-right'>

      <% if history && !current_user.is_self?(user)%>
        <%= link_to user_formulas_path(user), class: 'btn btn-sm btn-default', title: "User History" do %>
          <i class="fa fa-book"></i> <span class="hidden-sm hidden-xs">User</span> History
        <% end %>
      <% end %>

      <% unless current_user.is_self?(user) %>
        <%= link_to salon_connections_path(salon_user_id: user.id), class: 'btn btn-sm btn-success', method: :post, title: "Create Connection" do %>
          <i class="fa fa-user-plus"></i>
        <% end %>
      <% end %>

    </div>

  <% end %>

</div>

app/views/users/_user_listing.html.erb
<% if users.any? %>

  <% users.each_with_index do |user, index| %>
      <div class="col-xs-12 col-sm-6 col-md-4 panel-body">
          <div class="panel teal-border wht-bg mb-0">
              <div class="panel-body">
                      <div class="pull-left">
                          <%= link_to user_path(user) do %>
                            <% unless user.confirmed? %>
                              <small><i class="fa fa-hourglass-o"></i></small>
                            <% end %>
                                <% if user.first_name && user.last_name %>
                                    <%= user.full_name %><br>
                                <% else %>
                                    <small><%= user.email %></small><br>
                                <% end %>

                              <% if user.formulas %>
                                  <% if user.artist? %>
                                      <span class="text-muted small"><small><%= user.guest_formulas.size %> formulas accross <%= pluralize(user.connection_ids.size, 'guests') %></small></span>
                                  <% else %>
                                      <span class="text-muted small"><small><%= user.formulas.size %> formulas accross <%= pluralize(user.inverse_salon_connections.count, 'artist') %></small></span>
                                  <% end %>
                              <% end %>

                          <% end %>
                      </div>
                  <div class="text-right col-xs-12 user-links pull-right row">

                      <% if current_user.salon_users.include?(user) || current_user.inverse_salon_users.include?(user) %>
                          <% if current_user.artist? %>
                                  <%= link_to new_formula_path(requested_user: user), class: 'btn btn-danger', title: 'New Formula' do %>
                                      <%= icon('pencil-square-o') %><span class="hidden-xs"> New <span class="hidden-sm">Formula</span></span>
                                  <% end %>
                          <% end %>
                          <%= link_to salon_connection_path(id: user.id), class: 'btn btn-success', method: :delete, title: "Delete", data: {confirm: "remove #{user.full_name} from connections?"} do %>
                              <i class="fa fa-times"></i>
                          <% end %>

                      <% else %>
                              <%= link_to salon_connections_path(salon_user_id: user.id), class: 'btn btn-success blue-border', method: :post, title: "Connect" do %>
                                  <i class="fa fa-user-plus"></i>
                              <% end %>
                      <% end %>
                  </div>
          </div>
          </div>
        </div>

<% if index % 3 == 2 %>
<span class="hidden-xs hidden-sm clearfix"></span>
<% elsif index % 2 == 1 %>
<span class="visible-sm clearfix"></span>

<% end %>

  <% end %>
<% else %>
  <div class=" col-xs-12 col-sm-8 col-sm-offset-2 text-center">
    <span class="col-xs-12">No user found feel free to invite them!</span>

    <%= form_for( :user, as: :email, url: user_invitation_path ) do |f| %>
      <span class="input-group panel-body" >
          <%= f.label :email, class: 'input-group-addon' %>
          <%= f.text_field :email, class: 'form-control' %>
      </span>
      <%= f.submit 'Invite!', class: 'btn btn-success' %>
    <% end %>
  </div>
<% end %>

app/views/users/_user_search.html.erb
<div class="input-group">
  <%= form_tag(users_path, :method => "get", id: "user-search-form", enforce_utf8: false) do %>
    <%= text_field_tag :search, params[:search], options = { method: :get, class: 'form-control' } %>

      <%= button_tag( type: "submit", name: nil, class: 'form-control btn-success') do %>
        <i class="fa fa-search"></i>
      <% end %>
  <% end %>
</div>

app/views/users/_user_sidebar.html.erb
<table class="table services-list">
    <tr class="btn-scrollable">
        <th class="text-left">
          <span class="visible-xs">past <%= pluralize(formulas.size, ' formula') %></span>
          <span class="hidden-xs">services</span>
        </th>
        <th class="t-date text-right hidden-xs">date</th>
        <th class="t-date text-right visible-xs">
          <span class="visible-xs pull-right">
              scroll <i class="fa fa-sort"></i>
          </span>
        </th>
    </tr>

   <% formulas.each do |formula| %>
      <tr data-formula-id="<%= formula.id %>"
          data-formulation="<%= formula.formulation %>"
          data-formula-service="<%= formula.service_type %>"
          data-formula-date="<%= format_datetime(formula.created_at, 'md') %>"
          data-is-author="<%= current_user.id == formula.artist_id %>"
          data-formula-author="<%= formula.get_author_name %>"
          data-formula-client="<%= formula.get_client_name if formula.client_id %>"
          class= <%= "sidebar-bg" if formulas.first == formula %> >
          <td class="text-left">
            <%= link_to formula_path(formula), class: '' do %>
              <%= formula.service_type %>
            <% end %>
          </td>
          <td class="t-date text-right"><%= format_datetime(formula.created_at, 'md') %></td>
        </tr>
        <tr>
          <td colspan="2" class="td-no-border-top hidden-xs">
            <% if current_user.artist? %>
                <% if formula.client_id == formula.artist_id %>
                  <span class="text-muted small text-right"> personal </span>
                <% elsif current_user.author?(formula) %>
                  <span class="text-muted small">for:
                    <%= link_to user_path(formula.client_id) do %>
                      <%= formula.get_client_name %>
                    <% end %>
                  </span>
                <% else %>
                  <span class="text-muted small">by: <%= formula.get_author_name %> </span>
                <% end %>
            <% else %>
                <span class="text-muted small">by:
                  <%= link_to user_path(formula.artist_id) do %>
                    <%= formula.get_author_name %>
                  <% end %>
                </span>
            <% end %>

          </td>
      </tr>
   <% end %>

  </table>

app/views/users/edit.html.erb
<div class="col-xs-12">
    <div class="jumbotron">
        Edit profile info for: <%= @user.email %>
    </div>

    <div class="">
      Total guest formulas:
      <%= @user.guest_formulas.count %>
    </div>

    <%= link_to "edit", edit_user_registration_path %>
    <%= link_to "edit password", edit_user_password_path(@user) %>

    <div class="panel panel-default">
    <div class="panel-body">
        Dashboard information for other statistics
    </div>
    </div>

    <div class="panel panel-default">
    <div class="panel-body">
        Render form to update user info here
    </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-lg-8 col-lg-offset-2 text-center panel-body">
<div class="col-xs-12 col-sm-8 text-xs-center">
  <div class="col-xs-12 panel-body" >Displaying
        <% if current_user.client? %>
          <%= pluralize(@users.count, "artist") %>
        <% elsif current_user.artist? %>
          <%= pluralize(@users.count, "client") %>
        <% elsif current_user.admin? %>
            All <%= pluralize(@users.count, "users") %>
        <% end %>
  </div>
  </div>
    <div class="user-search">
      <%= render partial: 'user_search', locals: { user: current_user } %>
  </div>
</div>
<div id="user-listing" class="col-xs-12 col-sm-10 col-sm-offset-1 col-lg-8 col-lg-offset-2">
  <hr>
    <%= render partial: 'user_listing', locals: { users: @users, connection_ids: @connection_ids } %>
</div>

app/views/users/show.html.erb
 <div class="col-xs-12 col-lg-10 col-lg-offset-1 dashboard">


     <div class="col-xs-12 col-sm-9" id="main-panel">

         <% if current_user.is_self?(@user) %>
          <div class="visible-xs text-center">
              <%= link_to user_formulas_path(@user), class: 'btn btn-sm btn-default', title: "User History" do %>
                  <i class="fa fa-book"></i> Guest Formulas
              <% end %>
          </div>
        <% end %>

        <div id="user-header" class="panel-body">

            <div class="formula-guest-name">
                <% if current_user.is_self?(@user) %>
                    Your most recent formulas
                <% elsif @user.artist? && current_user.client? %>
                    Your most recent formula with:
                    <strong><%= @user.full_name %></strong>
                <% else %>
                    Formula<% if @formulas.size > 1 %><span class="hidden-xs">s</span><% end %> for: <%= @user.full_name %>
                <% end %>
            </div>

            <div id="formula-header" class="">
                <div class="formula-service-type">
                    <% if @formula %>
                        <span class="hidden-xs">
                            <%= @formula.service_type %><br>
                        </span>
                    <% else %>
                               User does not have any formulas yet.
                    <% end %>
                </div>
            </div>

            <!--User links-->
            <div class="user-links-partial">
              <%= render partial: 'user_links', locals: { user: @user, formula: @formula, history: true } %>
            </div>

         </div>

         <% if @formula %>
             <div class="formula-card-header">
                 f
             </div>
             <div id="formula-card-formulation" data-formula-id="<%= @formula.id %>" class="panel panel-body formula-card">
                 <div class="formula-service-type visible-xs text-center">
                   <span>
                     <%= @formula.service_type %>
                   </span>
                 </div>
                <hr class="visible-xs">
                 <div id="formula-formulation"><%= @formula.formulation %></div>
                 <div class='formula-card-footer pull-right'>
                    created on  <span class="formula-card-date"><%= format_datetime(@formula.created_at,'md') %></span> by <span class='formula-card-author'><%= @formula.get_author_name %></span>
                 </div>
             </div>
             <div id="formula-client-note" class="formula-note col-xs-12 well hidden">
                 <div class="note-header">
                     Note header [public/private] &amp; date_created
                 </div>
                 <div class="note-body">
                     Note body
                 </div>
             </div>
             <div id="formula-artist-note" class="formula-note col-xs-12 well hidden">
                 <div class="note-header">
                     Note header [public/private] &amp; date_created
                 </div>
                 <div class="note-body">
                     Note body
                 </div>
             </div>
        <% else %>
          <hr >
        <% end %>
     </div>

          <div id="sidebar" class="col-sm-3">

                 <div id="history-list" class="panel-body row">

                   <h4>
                     <% if @formulas %>
                       <span class="pull-left hidden-xs" ><%= pluralize(@formulas.size, 'formula') %></span>
                     <% else %>
                       no formulas available
                     <% end %>
                   </h4>

                   <% if @formulas %>
                     <%= render partial: 'user_sidebar', locals: { formulas: @formulas } %>
                   <% else %>
                     <hr>
                   <% end %>
                 </div>

          </div>

 </div>

 <% if current_user.artist? %>
  <%= render partial: 'formulas/quickjot', locals: { user: @user } %>
 <% end %>